Build Image from buildpack-deps and add more tools (#18)
* Build image from buildpack-deps

* install apt packages from toolset
- also add quiet parameter to all apt-get executions

* move labels into ci

* add toolsets

* remove unused build args

* just some cosmetics

* install node packages from toolset

* remove quotes from labels

* move npm install out of node install loop
- also use only one npm install for all pkgs, instead of loop
- add sha tag only for main
- small update to readme

* fix paths for global module permission fix

diff --git a/linux/ubuntu/Dockerfile b/linux/ubuntu/Dockerfile
--- a/linux/ubuntu/Dockerfile
+++ b/linux/ubuntu/Dockerfile
@@ -1,22 +1,122 @@
 # syntax=docker/dockerfile:1
-ARG FROM_IMAGE
-ARG FROM_FLAVOR
-ARG FROM_VERSION
-FROM --platform=$TARGETPLATFORM ${FROM_IMAGE}:${FROM_FLAVOR}-${FROM_VERSION}
 
-# add build arguments
+ARG FROM_IMAGE=buildpack-deps
+ARG FROM_VERSION_MAJOR=22
+ARG FROM_VERSION_MINOR=04
+ARG FROM_VERSION=${FROM_VERSION_MAJOR}.${FROM_VERSION_MINOR}
+FROM --platform=$TARGETPLATFORM ${FROM_IMAGE}:${FROM_VERSION} AS base
+
+# > automatic buildx ARGs
 ARG TARGETARCH
-ARG FROM_VERSION
 
-# set default shell to bash with pipefail and no profile
-SHELL ["/bin/bash", "--noprofile", "-e", "-o", "pipefail", "-c"]
+# > ARGs before FROM are not accessible
+ARG FROM_IMAGE
+ARG FROM_VERSION_MAJOR
+ARG FROM_VERSION_MINOR
+ARG FROM_VERSION=${FROM_VERSION_MAJOR}.${FROM_VERSION_MINOR}
+
+# > Our custom ARGs
+# latest Node.js LTS versions
+ARG NODE_VERSION="16 18"
+ARG DISTRO=ubuntu
+ARG CODENAME
+ARG TYPE=act
+
+# > Force apt to not be interactive/not ask
+ENV DEBIAN_FRONTEND=noninteractive
+
+SHELL [ "/bin/bash", "--login", "-e", "-o", "pipefail", "-c" ]
+WORKDIR /tmp
 
 # create targetproc file for later use
 RUN export targetarch=${TARGETARCH} \
     && if [ ${targetarch} = "amd64" ]; then export targetarch="x64"; fi \
     && echo ${targetarch} >/tmp/targetproc
 
-# install .NET SDK LTS
+# setup environment
+ENV AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache
+RUN sed 's|"||g' -i "/etc/environment" \
+    && echo "IMAGE_OS=${DISTRO}${FROM_VERSION_MAJOR}" | tee -a "/etc/environment" \
+    && echo "ImageOS=${DISTRO}${FROM_VERSION_MAJOR}" | tee -a "/etc/environment" \
+    && echo "LSB_RELEASE=${FROM_VERSION}" | tee -a "/etc/environment" \
+    && echo "AGENT_TOOLSDIRECTORY=${AGENT_TOOLSDIRECTORY}" | tee -a "/etc/environment" \
+    && echo "RUN_TOOL_CACHE=${AGENT_TOOLSDIRECTORY}" | tee -a "/etc/environment" \
+    && echo "DEPLOYMENT_BASEPATH=/opt/runner" | tee -a "/etc/environment" \
+    && echo "LSB_OS_VERSION=${FROM_VERSION_MAJOR}${FROM_VERSION_MINOR}" | tee -a "/etc/environment" \
+    && echo "USER=$(whoami)" | tee -a "/etc/environment" \
+    && echo "RUNNER_USER=$(whoami)" | tee -a "/etc/environment"
+
+# add ssh keys of github and azure devops
+# hadolint ignore=SC2174
+RUN mkdir -m 0700 -p ~/.ssh \
+    && ssh-keyscan -t rsa github.com >>/etc/ssh/ssh_known_hosts \
+    && ssh-keyscan -t rsa ssh.dev.azure.com >>/etc/ssh/ssh_known_hosts
+
+# Install Git-LFS
+RUN curl -Ls https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash \
+    && apt-get -yq install --no-install-recommends --no-install-suggests git-lfs \
+    && rm -rf /var/lib/apt/lists/*
+
+# Install dependencies
+RUN apt-get -yq update \
+    && packages=("ssh" "gawk" "curl" "jq" "wget" "sudo" "gnupg-agent" "ca-certificates" "software-properties-common" "apt-transport-https" "libyaml-0-2" "zstd" "zip" "unzip" "xz-utils") \
+    && apt-get -yq install \
+        --no-install-recommends \
+        --no-install-suggests \
+        "${packages[@]}" \
+    && rm -rf /var/lib/apt/lists/*
+
+# install apt packages from toolset
+COPY linux/${DISTRO}/toolsets/${FROM_VERSION_MAJOR}${FROM_VERSION_MINOR}.json /imagegeneration/toolset.json
+# hadolint ignore=SC2207
+RUN apt-get -yq update \
+    && packages=() && packages+=($(jq -r '.apt|.vital_packages[],.common_packages[],.cmd_packages[]' </imagegeneration/toolset.json)) \
+    && apt-get -yq install --no-install-recommends --no-upgrade "${packages[@]}" \
+    && ln -s "$(which python3)" "/usr/local/bin/python" \
+    && rm -rf /var/lib/apt/lists/*
+
+# Install docker cli
+RUN echo "deb https://packages.microsoft.com/ubuntu/$(lsb_release -rs)/prod $(lsb_release -cs) main" \
+    | tee /etc/apt/sources.list.d/microsoft-prod.list \
+    && curl -sL https://packages.microsoft.com/keys/microsoft.asc \
+    | gpg --dearmor >/etc/apt/trusted.gpg.d/microsoft.gpg \
+    && apt-get -yq update \
+    && apt-get -yq install --no-install-recommends --no-install-suggests \
+        moby-cli \
+        moby-buildx \
+        moby-compose \
+    && docker -v \
+    && docker buildx version \
+    && rm -rf /var/lib/apt/lists/*
+
+# Install Node.js and toolset packages
+# hadolint ignore=SC2174,DL3016
+RUN <<EOF
+IFS=' ' read -r -a NODE <<<"$NODE_VERSION"
+for ver in "${NODE[@]}"; do
+    printf "\n\t🐋 Installing Node.JS=%s 🐋\t\n" "${ver}"
+    VER=$(curl https://nodejs.org/download/release/index.json | jq "[.[] | select(.version|test(\"^v${ver}\"))][0].version" -r)
+    NODEPATH="$AGENT_TOOLSDIRECTORY/node/${VER:1}/$(cat /tmp/targetproc)"
+    mkdir -v -m 0777 -p "$NODEPATH"
+    curl -Ls "https://nodejs.org/download/release/latest-v${ver}.x/node-$VER-linux-$(cat /tmp/targetproc).tar.xz" -o "node-$VER-linux-$(cat /tmp/targetproc).tar.xz"
+    tar -Jxf "node-$VER-linux-$(cat /tmp/targetproc).tar.xz" --strip-components=1 -C "$NODEPATH"
+    rm "node-$VER-linux-$(cat /tmp/targetproc).tar.xz"
+    if [[ "${ver}" == "18" ]]; then  # make this version the default (latest LTS)
+        sed "s|^PATH=|PATH=$NODEPATH/bin:|mg" -i /etc/environment
+        ln -s "$NODEPATH/bin/node" /usr/local/bin/node
+    fi
+    export PATH="$NODEPATH/bin:$PATH"
+done
+# install packages from toolset
+packages=()
+while IFS='' read -r line; do packages+=("$line"); done < <(jq -r '.node_modules[].name' /imagegeneration/toolset.json)
+for package in "${packages[@]}"; do npm install -g "$package"; done
+chmod -R 777 $NODEPATH/lib/node_modules
+chmod -R 777 $NODEPATH/bin
+npm cache clean --force
+EOF
+
+# Set .NET related environment variables
 ENV DOTNET_ROOT=${AGENT_TOOLSDIRECTORY}/dotnet
 ENV PATH=${DOTNET_ROOT}:${PATH}
 ENV DOTNET_GENERATE_ASPNET_CERTIFICATE=false
@@ -24,12 +124,13 @@ ENV DOTNET_NOLOGO=true
 ENV DOTNET_SDK_VERSION=6.0.413
 ENV DOTNET_USE_POLLING_FILE_WATCHER=true
 ENV NUGET_XMLDOC_MODE=skip
-# hadolint ignore=DL3008
+
+# install .NET SDK LTS
 RUN export fromVersion=${FROM_VERSION} \
     && deps=("libc6" "libgcc1" "libgssapi-krb5-2" "libstdc++6" "zlib1g") \
     && if [ "${fromVersion}" = "20.04" ]; then deps+=("libicu66" "libssl1.1"); fi \
     && if [ "${fromVersion}" = "22.04" ]; then deps+=("libicu70" "libssl3" "libunwind8"); fi \
-    && apt-get update && apt-get install -y --no-install-recommends --no-upgrade "${deps[@]}" \
+    && apt-get -yq update && apt-get -yq install --no-install-recommends --no-upgrade "${deps[@]}" \
     && curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh \
     && chmod +x ./dotnet-install.sh \
     && ./dotnet-install.sh \
@@ -38,8 +139,9 @@ RUN export fromVersion=${FROM_VERSION} \
         --channel LTS \
         --version "${DOTNET_SDK_VERSION}" \
     && rm -rf ./dotnet-install.sh \
-    && rm -rf /var/lib/apt/lists/* \
-    && dotnet --info
+    && dotnet --info \
+    && sed "s|^PATH=|PATH=$DOTNET_ROOT:|mg" -i /etc/environment \
+    && rm -rf /var/lib/apt/lists/*
 
 # Install PowerShell global tool
 RUN export powershell_version=7.2.13 \
@@ -58,34 +160,28 @@ RUN export powershell_version=7.2.13 \
     && chmod 755 /usr/share/powershell/pwsh \
     && find /usr/share/powershell -print | grep -i '.*[.]nupkg$' | xargs rm
 
-# # Install Azure Powershell Modules
+# # Trust PSGallery and install Azure Powershell Modules
 RUN export azVersion=10.2.0 \
-    && pwsh \
-        -NonInteractive \
-        -NoProfile \
+    && pwsh -NonInteractive -NoProfile \
         -Command "Set-PSRepository -Name PSGallery -InstallationPolicy Trusted" \
-    && pwsh \
-        -NonInteractive \
-        -NoProfile \
+    && pwsh -NonInteractive -NoProfile \
         -Command "Install-Module -Name Az -RequiredVersion ${azVersion} -Scope AllUsers -Repository PSGallery"
 
 # Install Github CLI
-# hadolint ignore=DL3008
 RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
     && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
     && echo "deb [arch=$TARGETARCH signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list >/dev/null \
-    && apt-get update \
-    && apt-get install -y --no-install-recommends gh \
+    && apt-get -yq update \
+    && apt-get -yq install --no-install-recommends gh \
     && rm -rf /var/lib/apt/lists/*
 
 # Install Azure CLI
-# hadolint ignore=DL3008
 RUN [[ $(curl -sL https://packages.microsoft.com/repos/azure-cli/dists/) =~ $(lsb_release -cs) ]] \
     && (curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor >/etc/apt/trusted.gpg.d/microsoft.gpg \
         && echo "deb [arch=$(dpkg --print-architecture)] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" \
             >/etc/apt/sources.list.d/azure-cli.list \
-        && apt-get update \
-        && apt-get install -y --no-install-recommends azure-cli \
+        && apt-get -yq update \
+        && apt-get -yq install --no-install-recommends azure-cli \
         && az extension add -n azure-devops \
         && az bicep install --target-platform "linux-$(cat /tmp/targetproc)" \
         && az config set bicep.use_binary_from_path=true \
@@ -100,5 +196,17 @@ RUN curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep
     && chmod +x ./bicep \
     && mv ./bicep /usr/local/bin/bicep
 
-# clean tmp
-RUN rm -Rf /tmp/*
+# cleanup step
+RUN apt-get -yq clean \
+    && rm -rf \
+        /var/cache/* \
+        /var/log/* \
+        /var/lib/apt/lists/* \
+        /tmp/* \
+    || echo 'Failed to delete directories'
+
+ARG RUNNER
+USER ${RUNNER}
+
+# add environment variables to bashrc
+RUN echo ". /etc/environment" | tee -a /etc/bash.bashrc -a ~/.bashrc
