update versions, move locales to baseimage (#56)
- golang 1.20.9 (also fix arguments)
- pulumi 3.87.0
- .net sdk version 6.0.415
- don't delete dotnet - 15gb additional space by deleting android sdk should be enough
- use relative path for pwsh symlink
- use archive to compare PR with PR Target
- use scout to create sbom (since scout in dockerhub doesn't work otherwise)
- remove uneeded build args

diff --git a/linux/ubuntu/Dockerfile b/linux/ubuntu/Dockerfile
--- a/linux/ubuntu/Dockerfile
+++ b/linux/ubuntu/Dockerfile
@@ -1,10 +1,32 @@
 # syntax=docker/dockerfile:1
-# kics-scan disable=e36d8880-3f78-4546-b9a1-12f0745ca0d5,965a08d7-ef86-4f14-8792-4a3b2098937e,77783205-c4ca-4f80-bb80-c777f267c547
-ARG FROM_IMAGE=buildpack-deps
-ARG FROM_VERSION_MAJOR=22
-ARG FROM_VERSION_MINOR=04
-ARG FROM_VERSION=${FROM_VERSION_MAJOR}.${FROM_VERSION_MINOR}
-FROM ${FROM_IMAGE}:${FROM_VERSION} as base
+# kics-scan disable=e36d8880-3f78-4546-b9a1-12f0745ca0d5,965a08d7-ef86-4f14-8792-4a3b2098937e,77783205-c4ca-4f80-bb80-c777f267c547,0008c003-79aa-42d8-95b8-1c2fe37dbfe6
+ARG FROM_VERSION=22.04
+FROM buildpack-deps:${FROM_VERSION} as base
+
+# Force apt to not be interactive/not ask
+ENV DEBIAN_FRONTEND=noninteractive
+
+# Configure apt to always assume Y
+RUN echo "APT::Get::Assume-Yes \"true\";" >/etc/apt/apt.conf.d/90assumeyes
+
+# set locale
+ARG language=en_US
+RUN apt-get -y update >/dev/null \
+    && apt-get -y install --no-install-recommends \
+        locales \
+    && apt-get clean \
+    && rm -rf /etc/apt/sources.list.d/* \
+    && rm -rf /var/lib/apt/lists/* \
+    && localedef \
+        --inputfile="${language}" \
+        --force \
+        --charmap=UTF-8 \
+        --alias-file=/usr/share/locale/locale.alias "${language}.UTF-8"
+ENV LANG=${language}.utf8 \
+    LANGUAGE=${language} \
+    LC_ALL=${language}.utf8 \
+    RUNNER_MANUALLY_TRAP_SIG=1 \
+    ACTIONS_RUNNER_PRINT_LOG_TO_STDOUT=1
 
 FROM base as golang
 ARG TARGETARCH
@@ -47,32 +69,6 @@ FROM base as act-base
 # automatic buildx ARGs
 ARG TARGETARCH
 
-# ARGs used before `FROM` are not accessible afterwards
-ARG FROM_IMAGE
-ARG FROM_VERSION_MAJOR=22
-ARG FROM_VERSION_MINOR=04
-ARG FROM_VERSION=${FROM_VERSION_MAJOR}.${FROM_VERSION_MINOR}
-ARG DISTRO=ubuntu
-
-# Force apt to not be interactive/not ask
-ENV DEBIAN_FRONTEND=noninteractive
-
-# Configure apt to always assume Y
-RUN echo "APT::Get::Assume-Yes \"true\";" >/etc/apt/apt.conf.d/90assumeyes
-
-# set locale
-RUN apt-get update \
-    && apt-get install -y --no-install-recommends \
-        locales \
-    && rm -rf /var/lib/apt/lists/* \
-    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
-
-ENV LANG=en_US.UTF-8 \
-    LANGUAGE=en_US:en \
-    LC_ALL=en_US.UTF-8 \
-    RUNNER_MANUALLY_TRAP_SIG=1 \
-    ACTIONS_RUNNER_PRINT_LOG_TO_STDOUT=1
-
 # enable pipefail and set workdir
 SHELL [ "/bin/bash", "--login", "-e", "-o", "pipefail", "-c" ]
 WORKDIR /tmp
@@ -80,16 +76,24 @@ WORKDIR /tmp
 # setup environment
 ENV AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache \
     AZURE_EXTENSION_DIR=/opt/az/azcliextensions
-RUN locale | tee -a /etc/environment \
+RUN apt-get -y update \
+    && apt-get -y install --no-install-recommends \
+        lsb-release \
+    && apt-get clean \
+    && rm -rf /etc/apt/sources.list.d/* \
+    && rm -rf /var/lib/apt/lists/* \
+    && distro=$(lsb_release --id --short) \
+    && version=$(lsb_release --release --short) \
+    && locale | tee -a /etc/environment \
     && sed 's|"||g' -i "/etc/environment" \
-    && echo "IMAGE_OS=${DISTRO}${FROM_VERSION_MAJOR}" | tee -a /etc/environment \
-    && echo "ImageOS=${DISTRO}${FROM_VERSION_MAJOR}" | tee -a /etc/environment \
-    && echo "LSB_RELEASE=${FROM_VERSION}" | tee -a /etc/environment \
+    && echo "IMAGE_OS=${distro}${version::2}" | tee -a /etc/environment \
+    && echo "ImageOS=${distro}${version::2}" | tee -a /etc/environment \
+    && echo "LSB_RELEASE=${version}" | tee -a /etc/environment \
     && echo "AGENT_TOOLSDIRECTORY=${AGENT_TOOLSDIRECTORY}" | tee -a /etc/environment \
-    && echo "AZURE_EXTENSION_DIR=$AZURE_EXTENSION_DIR" | tee -a /etc/environment \
+    && echo "AZURE_EXTENSION_DIR=${AZURE_EXTENSION_DIR}" | tee -a /etc/environment \
     && echo "RUN_TOOL_CACHE=${AGENT_TOOLSDIRECTORY}" | tee -a /etc/environment \
     && echo "DEPLOYMENT_BASEPATH=/opt/runner" | tee -a /etc/environment \
-    && echo "LSB_OS_VERSION=${FROM_VERSION_MAJOR}${FROM_VERSION_MINOR}" | tee -a /etc/environment \
+    && echo "LSB_OS_VERSION=${version//./}" | tee -a /etc/environment \
     && echo "USER=$(whoami)" | tee -a /etc/environment \
     && echo "RUNNER_USER=$(whoami)" | tee -a /etc/environment \
     && echo "RUNNER_MANUALLY_TRAP_SIG=${RUNNER_MANUALLY_TRAP_SIG}" | tee -a /etc/environment \
@@ -103,8 +107,9 @@ RUN ssh-keyscan github.com >>/etc/ssh/ssh_known_hosts \
 # Install dependencies
 ARG DEPENDENCIES
 RUN apt-get -y update &>/dev/null \
-    && apt-get -y install --no-install-recommends jq && packages=() \
-    && while IFS='' read -r pkg; do echo "adding $pkg" && packages+=("$pkg"); done < <(echo "${DEPENDENCIES}" | jq -r '.[]') \
+    && apt-get -y install --no-install-recommends jq \
+    && packages=() \
+    && while IFS='' read -r pkg; do packages+=("$pkg"); done < <(printf "%s\n" "${DEPENDENCIES}" | jq -r '.[]') \
     && apt-get -y install --no-install-recommends \
         "${packages[@]}" \
     && apt-get clean \
@@ -154,7 +159,9 @@ RUN echo "deb https://packages.microsoft.com/ubuntu/$(lsb_release -rs)/prod $(ls
     && rm -rf /var/lib/apt/lists/*
 
 # Set .NET related environment variables
-ARG DOTNET_SDK_VERSION=6.0.414
+ARG DOTNET_SDK_VERSION=latest
+ARG DOTNET_CHANNEL=STS
+ARG DOTNET_DEPS
 ENV DOTNET_CLI_TELEMETRY_OPTOUT=1 \
     DOTNET_GENERATE_ASPNET_CERTIFICATE=false \
     DOTNET_HOST_PATH=${AGENT_TOOLSDIRECTORY}/dotnet/dotnet \
@@ -168,18 +175,17 @@ ENV DOTNET_CLI_TELEMETRY_OPTOUT=1 \
     NUGET_PACKAGES=${AGENT_TOOLSDIRECTORY}/nugetpackages \
     PATH=${AGENT_TOOLSDIRECTORY}/dotnet/tools:${AGENT_TOOLSDIRECTORY}/dotnet:${PATH}
 
-# install .NET SDK LTS
+# install .NET SDK
 RUN printf "Package: *net*\nPin: origin packages.microsoft.com\nPin-Priority: 1001\n" >/etc/apt/preferences.d/dotnet \
     && deps=("libc6" "libgcc1" "libgssapi-krb5-2" "libstdc++6" "zlib1g") \
-    && if [ "${FROM_VERSION}" = "20.04" ]; then deps+=("libicu66" "libssl1.1"); fi \
-    && if [ "${FROM_VERSION}" = "22.04" ]; then deps+=("libicu70" "libssl3" "libunwind8"); fi \
+    && while IFS='' read -r dep; do deps+=("$dep"); done < <(printf "%s\n" "${DOTNET_DEPS}" | jq -r '.[]') \
     && apt-get -y update &>/dev/null \
     && apt-get -y install --no-install-recommends \
         "${deps[@]}" \
     && curl -fsSL https://dot.net/v1/dotnet-install.sh | bash -s -- \
         --install-dir "${DOTNET_ROOT}" \
         --no-path \
-        --channel LTS \
+        --channel "${DOTNET_CHANNEL}" \
         --version "${DOTNET_SDK_VERSION}" \
     && rm -rf /etc/apt/preferences.d/dotnet \
     && sed "s|^PATH=|PATH=${DOTNET_ROOT}:|mg" -i /etc/environment \
@@ -272,7 +278,7 @@ RUN apt-get -y clean \
     || echo 'Failed to delete directories'
 
 # kics-scan ignore-line
-FROM act-base as powershell
+FROM act-base as act-powershell
 SHELL [ "/bin/bash", "--login", "-e", "-o", "pipefail", "-c" ]
 # Install PowerShell global tool
 ARG TARGETARCH
@@ -283,20 +289,32 @@ RUN dotnet tool install \
     --version "${POWERSHELL_VERSION}" \
     PowerShell \
     && find "${TOOL_PATH_PWSH}" -print | grep -i '.*[.]nupkg$' | xargs rm \
-    && ln -s "${TOOL_PATH_PWSH}/pwsh" /usr/local/bin/pwsh \
+    && ln -s "$(realpath --relative-to=/usr/local/bin "${TOOL_PATH_PWSH}")/pwsh" /usr/local/bin/pwsh \
     && chmod 755 "${TOOL_PATH_PWSH}/pwsh" \
     && [[ "$(pwsh --version)" =~ ${POWERSHELL_VERSION} ]]
+#     && pwsh -NonInteractive -Command "Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force -Scope AllUsers" \
 
 # kics-scan ignore-line
-FROM powershell as powershell-modules
+FROM act-powershell as act-powershell-modules
 ARG TARGETARCH
 SHELL [ "/bin/bash", "--login", "-e", "-o", "pipefail", "-c" ]
 ARG POWERSHELL_MODULES
+# Trust PSGallery and install Powershell-/Azure Modules
+RUN pwsh -NonInteractive -Command "Set-PSRepository -Name PSGallery -InstallationPolicy Trusted" \
+    && while IFS='' read -r pwshModule; do echo "installing ${pwshModule}" \
+        && pwsh -NonInteractive -Command "Install-Module -Name ${pwshModule} -Scope AllUsers -Repository PSGallery"; done \
+        < <(printf "%s\n" "${POWERSHELL_MODULES}" | jq -r '.[]')
+
+# kics-scan ignore-line
+FROM act-powershell as act-powershell-az-modules
+ARG TARGETARCH
+SHELL [ "/bin/bash", "--login", "-e", "-o", "pipefail", "-c" ]
 ARG POWERSHELL_AZ_MODULE_VERSIONS
 # Trust PSGallery and install Powershell-/Azure Modules
 RUN pwsh -NonInteractive -Command "Set-PSRepository -Name PSGallery -InstallationPolicy Trusted" \
-    && while IFS='' read -r pwshModule; do echo "installing ${pwshModule}" && pwsh -NonInteractive -Command "Install-Module -Name ${pwshModule} -Scope AllUsers -Repository PSGallery"; done < <(echo "${POWERSHELL_MODULES}" | jq -r '.[]') \
-    && while IFS='' read -r azVersion; do echo "installing Az ${azVersion}" && pwsh -NonInteractive -Command "Install-Module -Name Az -RequiredVersion ${azVersion} -Scope AllUsers -Repository PSGallery"; done < <(echo "${POWERSHELL_AZ_MODULE_VERSIONS}" | jq -r '.[]')
+    && while IFS='' read -r azVersion; do echo "installing Az ${azVersion}" \
+        && pwsh -NonInteractive -Command "Install-Module -Name Az -RequiredVersion ${azVersion} -Scope AllUsers -Repository PSGallery"; done \
+        < <(printf "%s\n" "${POWERSHELL_AZ_MODULE_VERSIONS}" | jq -r '.[]')
 
 # kics-scan ignore-line
 FROM act-base as act
@@ -317,11 +335,12 @@ COPY --from=bicep /usr/local/bin/bicep /usr/local/bin/bicep
 
 # add PowerShell
 ARG TOOL_PATH_PWSH=/usr/share/powershell
-COPY --from=powershell ${TOOL_PATH_PWSH} ${TOOL_PATH_PWSH}
-RUN ln -s "${TOOL_PATH_PWSH}/pwsh" /usr/local/bin/pwsh
+COPY --from=act-powershell ${TOOL_PATH_PWSH} ${TOOL_PATH_PWSH}
+RUN ln -s "$(realpath --relative-to=/usr/local/bin "${TOOL_PATH_PWSH}")/pwsh" /usr/local/bin/pwsh
 
 # add  PowerShell-modules
-COPY --from=powershell-modules /usr/local/share/powershell /usr/local/share/powershell
+COPY --from=act-powershell-modules /usr/local/share/powershell /usr/local/share/powershell
+COPY --from=act-powershell-az-modules /usr/local/share/powershell /usr/local/share/powershell
 
 ARG RUNNER
 USER ${RUNNER}
